# Generated by Django 5.2.9 on 2025-12-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, help_text='The actual person buying the food', max_length=100, null=True),
        ),
    ]
