# Generated by Django 5.2.9 on 2025-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
